# Generated by Django 5.2.8 on 2026-10-02 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0008_campaignrun"),
        ("email_engine", "0002_remove_legacy_lead_relationship"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaillog",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="campaigns.campaign",
            ),
        ),
    ]
