# Generated by Django 5.1.3 on 2026-07-30 22:10

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_customuser_email_preferences_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="fiat_balance_usd",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("10000.00"), max_digits=15
            ),
        ),
        migrations.CreateModel(
            name="P2PEscrow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset", models.CharField(max_length=10)),
                ("amount", models.DecimalField(decimal_places=8, max_digits=20)),
                ("released", models.BooleanField(default=False)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escrow",
                        to="users.p2porder",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escrows",
                        to="users.walletasset",
                    ),
                ),
            ],
            options={
                "db_table": "p2p_escrows",
                "ordering": ["-created_at"],
            },
        ),
    ]
