# Generated by Django 5.1.3 on 2026-08-02 10:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_customuser_fiat_balance_usd_p2pescrow"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="fiat_balance_usd",
        ),
    ]
