# Generated by Django 5.1.3 on 2026-08-06 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_remove_customuser_fiat_balance_usd"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                ("message_count", models.IntegerField(default=0)),
                ("unread_count", models.IntegerField(default=0)),
                ("last_seen_by_buyer", models.DateTimeField(blank=True, null=True)),
                ("last_seen_by_seller", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_rooms_as_buyer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_rooms_as_seller",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trade",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_room",
                        to="users.p2porder",
                    ),
                ),
            ],
            options={
                "db_table": "chat_rooms",
                "ordering": ["-last_message_at"],
            },
        ),
        migrations.CreateModel(
            name="Dispute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(max_length=200)),
                ("reason_detail", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("IN_PROGRESS", "In Progress"),
                            ("RESOLVED", "Resolved"),
                            ("CLOSED", "Closed"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "action_taken",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("notification_to_buyer", models.BooleanField(default=False)),
                ("notification_to_seller", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_disputes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "initiator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="initiated_disputes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disputes",
                        to="users.p2porder",
                    ),
                ),
            ],
            options={
                "db_table": "disputes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DisputeEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evidence_type",
                    models.CharField(
                        choices=[
                            ("payment_proof", "Payment Proof"),
                            ("chat_transcript", "Chat Transcript"),
                            ("document", "Document"),
                        ],
                        max_length=30,
                    ),
                ),
                ("file_url", models.URLField()),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="users.dispute",
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispute_evidence_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "dispute_evidence",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InternalTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset", models.CharField(max_length=10)),
                ("amount", models.DecimalField(decimal_places=18, max_digits=36)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internal_transfers_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_as_recipient",
                        to="users.transaction",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internal_transfers_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_as_sender",
                        to="users.transaction",
                    ),
                ),
            ],
            options={
                "db_table": "internal_transfers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=100)),
                ("body", models.TextField(blank=True, default="")),
                ("data", models.JSONField(blank=True, default=dict)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("delivered", models.BooleanField(default=False)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("DELIVERED", "Delivered"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="P2POffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset", models.CharField(max_length=10)),
                (
                    "intent",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")], max_length=10
                    ),
                ),
                (
                    "price_type",
                    models.CharField(
                        choices=[
                            ("FIXED", "Fixed Price"),
                            ("MARKET", "Market Price"),
                            ("PREMIUM", "Premium"),
                        ],
                        default="FIXED",
                        max_length=20,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=18, null=True
                    ),
                ),
                (
                    "premium_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("min_amount", models.DecimalField(decimal_places=8, max_digits=20)),
                ("max_amount", models.DecimalField(decimal_places=8, max_digits=20)),
                ("payment_method_ids", models.JSONField(blank=True, default=list)),
                ("terms", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("PAUSED", "Paused"),
                            ("DEACTIVATED", "Deactivated"),
                            ("EXHAUSTED", "Exhausted"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("PUBLIC", "Public"), ("PRIVATE", "Private")],
                        default="PUBLIC",
                        max_length=20,
                    ),
                ),
                (
                    "total_volume",
                    models.DecimalField(decimal_places=18, default=0, max_digits=36),
                ),
                ("completed_trades", models.IntegerField(default=0)),
                ("duration", models.IntegerField(default=3600)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="p2p_offers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "p2p_offers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.URLField(unique=True)),
                ("p256dh", models.CharField(max_length=255)),
                ("auth", models.CharField(max_length=255)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "push_subscriptions",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField()),
                ("comment", models.TextField()),
                ("tags", models.JSONField(blank=True, default=list)),
                ("verified", models.BooleanField(default=True)),
                ("reported", models.BooleanField(default=False)),
                ("reported_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "advertiser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submitted_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trade",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="users.p2porder",
                    ),
                ),
            ],
            options={
                "db_table": "reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TransactionTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_language", models.CharField(max_length=10)),
                ("source_text", models.TextField()),
                ("translated_text", models.TextField()),
                (
                    "translation_type",
                    models.CharField(
                        choices=[
                            ("description", "Description"),
                            ("note", "Note"),
                            ("extra", "Extra"),
                        ],
                        default="description",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_translations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="users.transaction",
                    ),
                ),
            ],
            options={
                "db_table": "translations",
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("image", "Image"),
                            ("payment_proof", "Payment Proof"),
                            ("system", "System"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("attachment_url", models.URLField(blank=True, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "chat_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="users.chatroom",
                    ),
                ),
            ],
            options={
                "db_table": "chat_messages",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["chat_room", "-created_at"], name="idx_chat_msg_room"
                    ),
                    models.Index(
                        fields=["sender", "-created_at"], name="idx_chat_msg_sender"
                    ),
                    models.Index(
                        fields=["chat_room", "is_read", "-created_at"],
                        name="idx_chat_msg_read",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DeviceFingerprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_agent", models.TextField()),
                ("browser", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "browser_version",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("os", models.CharField(blank=True, max_length=50, null=True)),
                ("os_version", models.CharField(blank=True, max_length=50, null=True)),
                ("device_type", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "screen_resolution",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("language", models.CharField(blank=True, max_length=50, null=True)),
                ("timezone", models.CharField(blank=True, max_length=50, null=True)),
                ("platform", models.CharField(blank=True, max_length=50, null=True)),
                ("cores", models.IntegerField(blank=True, null=True)),
                ("memory", models.IntegerField(blank=True, null=True)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "location_city",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "location_country",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "location_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=9, null=True
                    ),
                ),
                (
                    "location_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=9, null=True
                    ),
                ),
                ("location_accuracy", models.IntegerField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_fingerprints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "security_fingerprints",
                "ordering": ["-last_seen"],
                "indexes": [
                    models.Index(fields=["user", "-last_seen"], name="idx_fp_user"),
                    models.Index(fields=["ip_address", "-last_seen"], name="idx_fp_ip"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(fields=["trade"], name="idx_disputes_trade"),
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(
                fields=["status", "-created_at"], name="idx_disputes_status"
            ),
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(fields=["admin", "status"], name="idx_disputes_admin"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read", "-created_at"], name="idx_notif_user"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["type", "user"], name="idx_notif_type"),
        ),
        migrations.AddIndex(
            model_name="p2poffer",
            index=models.Index(
                fields=["user", "status", "-created_at"], name="idx_p2p_offers_user"
            ),
        ),
        migrations.AddIndex(
            model_name="p2poffer",
            index=models.Index(
                fields=["asset", "intent", "status", "price"],
                name="idx_p2p_offers_market",
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["advertiser", "-rating"], name="idx_reviews_advertiser"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["trade"], name="idx_reviews_trade"),
        ),
        migrations.AddIndex(
            model_name="transactiontranslation",
            index=models.Index(
                fields=["transaction", "target_language"], name="idx_translations_tx"
            ),
        ),
        migrations.AddIndex(
            model_name="transactiontranslation",
            index=models.Index(fields=["-created_at"], name="idx_translations_created"),
        ),
        migrations.AlterUniqueTogether(
            name="transactiontranslation",
            unique_together={("transaction", "target_language", "translation_type")},
        ),
    ]
