# Generated by Django 5.1.3 on 2026-08-09 02:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_fix_transaction_created_at_auto_now_add"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("deposit", "Deposit"),
                    ("withdrawal", "Withdrawal"),
                    ("transfer_in", "Transfer In"),
                    ("transfer_out", "Transfer Out"),
                    ("buy", "Buy"),
                    ("swap", "Swap"),
                    ("receive", "Receive"),
                    ("send", "Send"),
                ],
                max_length=20,
            ),
        ),
    ]
