# Generated by Django 5.1.3 on 2026-08-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_add_receive_send_transaction_types"),
    ]

    operations = [
        # Drop the P2P models (DeleteModel handles all fields, indexes, and tables)
        migrations.DeleteModel(
            name="ChatMessage",
        ),
        migrations.DeleteModel(
            name="ChatRoom",
        ),
        migrations.DeleteModel(
            name="DisputeEvidence",
        ),
        migrations.DeleteModel(
            name="Dispute",
        ),
        migrations.DeleteModel(
            name="P2PEscrow",
        ),
        migrations.DeleteModel(
            name="P2POffer",
        ),
        migrations.DeleteModel(
            name="P2POrder",
        ),
        migrations.DeleteModel(
            name="Review",
        ),
        # Update UserActivityLog action choices to remove P2P actions
        migrations.AlterField(
            model_name="useractivitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("password_change", "Password Change"),
                    ("password_reset_request", "Password Reset Request"),
                    ("password_reset_complete", "Password Reset Complete"),
                    ("2fa_enable", "2FA Enabled"),
                    ("2fa_disable", "2FA Disabled"),
                    ("avatar_update", "Avatar Updated"),
                    ("profile_update", "Profile Updated"),
                    ("kyc_submit", "KYC Submitted"),
                    ("kyc_approved", "KYC Approved"),
                    ("kyc_rejected", "KYC Rejected"),
                    ("session_revoke", "Session Revoked"),
                    ("session_revoke_all", "All Sessions Revoked"),
                    ("deposit", "Deposit"),
                    ("withdrawal", "Withdrawal"),
                    ("transfer", "Transfer"),
                    ("buy", "Buy Crypto"),
                    ("swap", "Swap Crypto"),
                ],
                max_length=30,
            ),
        ),
    ]