# Generated by Django 5.1.3 on 2026-08-15 06:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_remove_p2p_tables"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="fee",
            field=models.DecimalField(
                decimal_places=8, default=Decimal("0"), max_digits=20
            ),
        ),
    ]
