# Generated by Django 5.1.3 on 2026-08-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_alter_transaction_fee"),
    ]

    operations = [
        # Step 1: Add field without unique constraint, allow blank
        migrations.AddField(
            model_name="customuser",
            name="public_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Public-facing alphanumeric user ID",
                max_length=20,
                default="",
            ),
        ),
    ]
