# Generated by Django 5.1.3 on 2026-08-18 11:36

from django.db import migrations
import secrets
import string


def generate_public_id():
    """Generate a unique 14-character alphanumeric public ID."""
    alphabet = string.ascii_letters + string.digits  # 62 characters
    return ''.join(secrets.choice(alphabet) for _ in range(14))


def backfill_public_ids(apps, schema_editor):
    """Generate unique public_id for existing users."""
    CustomUser = apps.get_model("users", "CustomUser")
    
    # Get all users without a public_id
    users_without_id = CustomUser.objects.filter(public_id="")
    
    for user in users_without_id:
        # Generate unique public_id
        for _ in range(10):
            candidate = generate_public_id()
            if not CustomUser.objects.filter(public_id=candidate).exists():
                user.public_id = candidate
                user.save(update_fields=["public_id"])
                break


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_customuser_public_id"),
    ]

    operations = [
        migrations.RunPython(backfill_public_ids, migrations.RunPython.noop),
    ]
