# Generated by Django 5.1.3 on 2026-08-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_backfill_public_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="public_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Public-facing alphanumeric user ID",
                max_length=20,
                unique=True,
            ),
        ),
    ]
