# Generated by Django 5.1.3 on 2026-09-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_campaignaccesstoken_use_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
