# Generated by Django 5.1.3 on 2026-09-29 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0022_remove_account_public_id_and_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeletionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Deleted at"),
                ),
                (
                    "deletion_reason",
                    models.TextField(blank=True, verbose_name="Reason"),
                ),
                (
                    "client_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Client IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_deletions",
                        to="users.deletionhistory",
                        verbose_name="Deleted by",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="deletion_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Deletion Record",
                "verbose_name_plural": "Deletion Records",
                "db_table": "deletion_history",
                "ordering": ["-deleted_at"],
                "indexes": [
                    models.Index(fields=["deleted_at"], name="idx_del_deleted_at"),
                    models.Index(fields=["user"], name="idx_del_user"),
                ],
            },
        ),
    ]
