# Generated by Django 4.2.7 on 2026-07-11 15:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnsubscribedLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, help_text='Where the unsubscribe came from', max_length=255, null=True)),
                ('unsubscribed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Unsubscribed Lead',
                'verbose_name_plural': 'Unsubscribed Leads',
                'ordering': ['-unsubscribed_at'],
            },
        ),
    ]
