# Generated by Django 4.2.7 on 2026-07-11 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0001_initial"),
        ("app_templates", "0001_initial"),
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="batch_size",
            field=models.IntegerField(
                default=50, help_text="Number of emails per batch"
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="current_document_id",
            field=models.IntegerField(
                default=1, help_text="Currently processing document (1-20)"
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="email_per_day",
            field=models.IntegerField(default=450),
        ),
        migrations.AddField(
            model_name="campaign",
            name="email_per_hour",
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name="campaign",
            name="is_paused",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="campaign",
            name="last_processed_index",
            field=models.IntegerField(
                default=0, help_text="Last lead ID processed for resume support"
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="split_ratio",
            field=models.FloatField(
                default=0.5, help_text="Ratio for template A vs B (0.5 = 50/50)"
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="template_b",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaigns_template_b",
                to="app_templates.emailtemplate",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="throttle_per_minute",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="campaign",
            name="unsubscribe_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="campaign",
            name="warmup_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="campaign",
            name="warmup_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaigns_template_a",
                to="app_templates.emailtemplate",
            ),
        ),
        migrations.CreateModel(
            name="CampaignLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "template_variant",
                    models.CharField(
                        choices=[("A", "Variant A"), ("B", "Variant B")],
                        default="A",
                        max_length=1,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("opened", "Opened"),
                            ("clicked", "Clicked"),
                            ("failed", "Failed"),
                            ("bounced", "Bounced"),
                            ("unsubscribed", "Unsubscribed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("retry_count", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("clicked_at", models.DateTimeField(blank=True, null=True)),
                ("unsubscribed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_leads",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_leads",
                        to="leads.lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaign Lead",
                "verbose_name_plural": "Campaign Leads",
                "indexes": [
                    models.Index(
                        fields=["campaign", "status"],
                        name="campaigns_c_campaig_887c8a_idx",
                    ),
                    models.Index(
                        fields=["campaign", "sent_at"],
                        name="campaigns_c_campaig_18dd07_idx",
                    ),
                ],
                "unique_together": {("campaign", "lead")},
            },
        ),
    ]
