# Generated by Django 4.2.7 on 2026-07-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_batch_size_campaign_current_document_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Archived campaigns are hidden from normal workflows'),
        ),
    ]
