# Generated by Codex on 2026-07-20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaign_is_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='warmup_enabled',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='warmup_start_date',
        ),
    ]
