# Generated by Django 5.2.8 on 2026-10-02 07:35

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0007_alter_campaignlead_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("campaign_id", models.PositiveBigIntegerField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("cancel_requested", models.BooleanField(default=False)),
                ("process_id", models.PositiveIntegerField(blank=True, null=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "heartbeat_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["campaign_id", "status"],
                        name="campaigns_c_campaig_e08296_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "running")),
                        fields=("campaign_id",),
                        name="unique_active_campaign_run",
                    )
                ],
            },
        ),
    ]
