# Generated by Django 4.2.7 on 2026-07-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('subject', models.CharField(max_length=500)),
                ('html_content', models.TextField(help_text='HTML content with placeholders like {{first_name}}, {{last_name}}')),
                ('plain_text', models.TextField(blank=True, help_text='Plain text fallback version', null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('is_active', models.BooleanField(default=True)),
                ('spam_score', models.FloatField(default=0.0, help_text='Spam score from spam check')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'ordering': ['-created_at'],
            },
        ),
    ]
