# Generated by Django 5.1.3 on 2026-09-29 23:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_templates", "0002_emailtemplate_include_account_report_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="include_account_report_attachment",
            field=models.BooleanField(
                default=False,
                help_text="Generate and attach each recipient's personalized account report PDF to campaign and test emails.",
                verbose_name="Attach personalized account report (PDF)",
            ),
        ),
    ]
